// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlE2i9bnIukchjLrKuExxvGmIS5xteHi4',
    appId: '1:199001911351:web:1eca72c59ff84bcdb04fb2',
    messagingSenderId: '199001911351',
    projectId: 'mini-e-commerce-d6b9d',
    authDomain: 'mini-e-commerce-d6b9d.firebaseapp.com',
    storageBucket: 'mini-e-commerce-d6b9d.firebasestorage.app',
    measurementId: 'G-P9FFGRQDNL',
    databaseURL: 'https://mini-e-commerce-d6b9d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSIl54S05_Aozx4T23vx5WQR2HLthE4o',
    appId: '1:199001911351:android:399d46d862fd0151b04fb2',
    messagingSenderId: '199001911351',
    projectId: 'mini-e-commerce-d6b9d',
    storageBucket: 'mini-e-commerce-d6b9d.firebasestorage.app',
    databaseURL: 'https://mini-e-commerce-d6b9d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5plxYacobQqAuaRgyQs6Tnx2c5LrWwog',
    appId: '1:199001911351:ios:3799884d9f92ff48b04fb2',
    messagingSenderId: '199001911351',
    projectId: 'mini-e-commerce-d6b9d',
    storageBucket: 'mini-e-commerce-d6b9d.firebasestorage.app',
    iosBundleId: 'com.example.miniEcommerce',
    databaseURL: 'https://mini-e-commerce-d6b9d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5plxYacobQqAuaRgyQs6Tnx2c5LrWwog',
    appId: '1:199001911351:ios:3799884d9f92ff48b04fb2',
    messagingSenderId: '199001911351',
    projectId: 'mini-e-commerce-d6b9d',
    storageBucket: 'mini-e-commerce-d6b9d.firebasestorage.app',
    iosBundleId: 'com.example.miniEcommerce',
    databaseURL: 'https://mini-e-commerce-d6b9d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlE2i9bnIukchjLrKuExxvGmIS5xteHi4',
    appId: '1:199001911351:web:e49f72eab8d7e38db04fb2',
    messagingSenderId: '199001911351',
    projectId: 'mini-e-commerce-d6b9d',
    authDomain: 'mini-e-commerce-d6b9d.firebaseapp.com',
    storageBucket: 'mini-e-commerce-d6b9d.firebasestorage.app',
    measurementId: 'G-8599N9X3JZ',
    databaseURL: 'https://mini-e-commerce-d6b9d-default-rtdb.firebaseio.com',
  );
}
